### ISSUE TITLE
Selecting DOM by user given CSS selector

### ISSUE THREAD

**Issue by al123xiaaaa** [alexcodito/KnockoutContextHover#5]
I'm using syncfusion UI component with knockout,but most the data-bind DOM in html is a with:0 & height:0 block.I can't select the DOM by mouse hover.

**Comment by alexcodito** [comment]
I appreciate this may not be exactly what you're asking for, but I have now added buttons for traversing nodes manually. This has been useful to me for nodes that are difficult to highlight with mouse hover and it will likely meet your needs too. Feel free to contribute your changes to this repo.
