### ISSUE TITLE
Alphabetize properties

### ISSUE THREAD

**Issue by preeder** [alexcodito/KnockoutContextHover#8]
It is difficult to find the things you need to find when there is a large context with lots of properties.  It would be nice if the properties were alphabetized, or perhaps had an option to alphabetize the context.

**Comment by alexcodito** [comment]
Hello preeder. Thanks for your suggestion. This shouldn't be too effortful so I'll aim to include this as part of a larger future update.

**Comment by alexcodito** [comment]
This feature is now implemented in version 1.8.
